## **Antarctic Plateau Salt Relative Humidity and Temperature Dataset (APSRHT) - Cleaning**

Dataset: Davila, A; Parro, V. Antarctic Plateau-Salt Relative Humidity and Temperature. Astrobiology Habitable Environment Database. Retrieved Date: Jun 23, 2026. https://doi.org/10.48667/sy0j-yc84

"First column is the measurement number. Second column is the date/time of each measurement. Third column is the temperature in degrees Celssius. Fourth column is the RH as measured by the sensor. Fifth column is the RH with respect to ice"

In [38]:
import numpy as np
import pandas as pd

In [43]:
df = pd.read_csv('Antarctic_Plateau_Salt data.csv', encoding='latin1')
df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)
df

0         #      Date Time   T (¼C)  RH (%) RH (ice) (%)
0     11549  12/19/18 0:00  -20.167  53.306        64.41
1     11550  12/19/18 0:15  -20.073  53.239        64.29
2     11551  12/19/18 0:30  -19.839  53.167        64.06
3     11552  12/19/18 0:45    -19.7  53.189        63.99
4     11553  12/19/18 1:00  -19.469  53.389        64.04
...     ...            ...      ...     ...          ...
4411  15960   2/2/19 22:45  -34.677  54.135        74.68
4412  15961   2/2/19 23:00  -34.593  54.226        74.71
4413  15962   2/2/19 23:15  -34.427  54.357        74.73
4414  15963   2/2/19 23:30  -34.262  54.487        74.76
4415  15964   2/2/19 23:45  -34.098  54.617        74.78

[4416 rows x 5 columns]

In [44]:
### rename columns
df = df.rename(columns={'#': 'measurement_number', 'Date Time': 'date_time', 'T (¼C)': 'temp_C', 'RH (%)': 'relative_hum_NaCl', 'RH (ice) (%)': 'relative_hum_Ice'})
df.head()

,measurement_number,date_time,temp_C,relative_hum_NaCl,relative_hum_Ice
0,11549,12/19/18 0:00,-20.167,53.306,64.41
1,11550,12/19/18 0:15,-20.073,53.239,64.29
2,11551,12/19/18 0:30,-19.839,53.167,64.06
3,11552,12/19/18 0:45,-19.7,53.189,63.99
4,11553,12/19/18 1:00,-19.469,53.389,64.04

In [45]:
### convert to datetime
df['date_time'] = pd.to_datetime(df['date_time'], format='%m/%d/%y %H:%M')

### sort and set index
df = df.sort_values('date_time')
df = df.set_index('date_time')

### set 15-minute frequency and fill missing logs
#### ARIMA will fail if a 15-minute slot is missing from the raw data
df = df.asfreq('15min')

### fill missing measurement values caused by missing slots
df = df.ffill() 
df.head()

,measurement_number,temp_C,relative_hum_NaCl,relative_hum_Ice
date_time,,,,
2018-12-19 00:00:00,11549,-20.167,53.306,64.41
2018-12-19 00:15:00,11550,-20.073,53.239,64.29
2018-12-19 00:30:00,11551,-19.839,53.167,64.06
2018-12-19 00:45:00,11552,-19.7,53.189,63.99
2018-12-19 01:00:00,11553,-19.469,53.389,64.04

In [46]:
### write to .csv
df.to_csv('apsrht_datetime.csv', index=True, encoding='utf-8')